name: Slack Notifier

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      image_uri:
        required: false
        type: string
      environment:
        required: true
        type: string
      repository:
        required: true
        type: string
      commit_sha:
        required: true
        type: string
      commit_url:
        required: true
        type: string
      commit_message:
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        env:
          STATUS: ${{ inputs.status }}
          IMAGE_URI: ${{ inputs.image_uri }}
          ENVIRONMENT: ${{ inputs.environment }}
          REPOSITORY: ${{ inputs.repository }}
          COMMIT_SHA: ${{ inputs.commit_sha }}
          COMMIT_URL: ${{ inputs.commit_url }}
          COMMIT_MESSAGE: ${{ inputs.commit_message }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ "$STATUS" == "start" ]; then
            TEXT="Repo \`$REPOSITORY\` deploy to *$ENVIRONMENT* started\nCommit: <$COMMIT_URL|$COMMIT_SHA>\nMessage: \`$COMMIT_MESSAGE\`"
          elif [ "$STATUS" == "success" ]; then
            TEXT="Repo \`$REPOSITORY\` deploy to *$ENVIRONMENT* successful\nCommit: <$COMMIT_URL|$COMMIT_SHA>\nMessage: \`$COMMIT_MESSAGE\`\nImage: \`$IMAGE_URI\`"
          else
            TEXT="Repo \`$REPOSITORY\` deploy to *$ENVIRONMENT* failed\nCommit: <$COMMIT_URL|$COMMIT_SHA>\nMessage: \`$COMMIT_MESSAGE\`\nImage: \`$IMAGE_URI\`"
          fi

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$TEXT\"}" \
            $SLACK_WEBHOOK_URL

